# Fase 1: build del frontend
FROM node:22 AS builder

# Copia tutto il progetto nella directory di build
COPY . /build

# Imposta la directory di lavoro
WORKDIR /build/frontend

# Installa le dipendenze e compila il progetto
RUN npm ci
RUN npm run build

# Fase 2: runtime con Nginx
FROM nginx:alpine

# Copia i file statici generati nella directory di Nginx
COPY --from=builder /build/frontend/dist /usr/share/nginx/html

# Copia la configurazione personalizzata di Nginx
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

# Espone la porta HTTP
EXPOSE 80
