
services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: always
    ports:
      - "8080:80"   # frontend disponibile su http://localhost:8080
    depends_on:
      - backend
    deploy:
      replicas: 1   # puoi scalare se vuoi

  backend:
    image: applicazione
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      DB_URI: mongodb://mongodb:27017/tutoring
    ports:
      - "3000:3000"  # backend disponibile su http://localhost:3000
    depends_on:
      - mongodb
    deploy:
      replicas: 1

  mongodb:
    image: mongo
    restart: always
    command: [ "--bind_ip_all", "--port", "27017" ]
    volumes:
      - mongodata:/data/db

  mongoexpress:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/tutoring
    ports:
      - "8081:8081"   # interfaccia Mongo Express su http://localhost:8081
    depends_on:
      - mongodb
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongodata:
