FROM node:18

# Directory dove vivrà il codice nel container
WORKDIR /app

# Copio package.json e package-lock.json
COPY package*.json ./

# Installo le dipendenze
RUN npm install

# Copio tutto il backend
COPY . .

# Espongo la porta del server
EXPOSE 4000

# Comando di avvio
CMD ["npm", "start"]
