# Stage 1: Install dependencies
FROM oven/bun:1.2.0-alpine AS builder

# Imposta la cartella di lavoro
WORKDIR /app

# Copia tutti i file nel container
COPY . .

# Installa le dipendenze (rispettando il lockfile)
RUN bun install --frozen-lockfile

# Stage 2: Runtime
FROM node:22-alpine AS runner

# Imposta la cartella di lavoro
WORKDIR /app/backend

# Copia i file del backend (codice sorgente + dipendenze)
COPY --from=builder /app/backend ./

# Espone la porta dell’applicazione
ENV APP_PORT=3000
EXPOSE 3000

# Comando di default per avviare il server
CMD ["node", "bin/www"]
