# Usa un'immagine base leggera di Node.js
FROM node:22-alpine

# Imposta la directory di lavoro
WORKDIR /app

# Imposta la variabile d'ambiente per il database
ENV MONGODB_URI="mongodb://mongodb:27017/tutoring"

# Installa le dipendenze
RUN npm install

# Copia il resto del codice dell'app nel container
COPY . .

# Compila i file TypeScript
WORKDIR /app/models
RUN ../node_modules/typescript/bin/tsc

WORKDIR /app/backend
RUN ../node_modules/typescript/bin/tsc

# Espone la porta su cui gira Express
EXPOSE 3000

# Avvia l'applicazione
CMD ["node", "app.js"]
